/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Clientes;
import Models.DaoClientes;
import Models.DaoProductos;
import Models.DaoUsuarios;
import Models.DaoVentas;
import Models.DetallesVenta;
import Models.Productos;
import Models.Usuarios;
import Models.Ventas;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class CoffeeHome extends javax.swing.JFrame {
    Clientes clien = new Clientes();
    DaoClientes daoClient = new DaoClientes();
    Productos prod = new Productos();
    DaoProductos daoProd = new DaoProductos();
    DefaultTableModel modelo = new DefaultTableModel();
    Ventas ven = new Ventas();
    DaoVentas daoVen = new DaoVentas();
    DetallesVenta detaVent = new DetallesVenta();
    Usuarios usuario = new Usuarios();
    DaoUsuarios daoUsuario = new DaoUsuarios();
    int item;
    double totalPagar = 0.00;
    /**
     * Creates new form CoffeeHome
     */
    public CoffeeHome() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INICIO = new javax.swing.JButton();
        CLIENTES = new javax.swing.JButton();
        PRODUCTOS = new javax.swing.JButton();
        NUEVAVENTA = new javax.swing.JButton();
        USUARIOS = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtBuscarProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jButtonNuevoCliente = new javax.swing.JButton();
        jButtonRegistrarCliente = new javax.swing.JButton();
        jButtonModificarCliente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccionClientes = new javax.swing.JTextPane();
        txtIdCli = new javax.swing.JTextField();
        txtBuscarCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EliminarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCodigoProd = new javax.swing.JTextField();
        txtNombreProd = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidadProd = new javax.swing.JTextField();
        jComboBoxMedidas = new javax.swing.JComboBox<>();
        jButtonNuevoProd = new javax.swing.JButton();
        jButtonRegistrarProd = new javax.swing.JButton();
        jButtonModificarProd = new javax.swing.JButton();
        txtIDProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonEliminarProd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableProductos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCodigoNV = new javax.swing.JTextField();
        txtNomProdNV = new javax.swing.JTextField();
        txtCantidadNV = new javax.swing.JTextField();
        txtMedidaNV = new javax.swing.JTextField();
        jButtonEliminarPedido = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtNombreCliNV = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtDireccionNV = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        LabelTotarPagar = new javax.swing.JLabel();
        txtTotalNV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPrecioNV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVentas = new javax.swing.JTable();
        txtClienteIdNV = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTelefonoNV = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtMesero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jButtonNuevoUsuario = new javax.swing.JButton();
        jButtonRegistrarUsu = new javax.swing.JButton();
        jButtonModificarUsuario = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtPasswordUs = new javax.swing.JTextField();
        jComboBoxRolUs = new javax.swing.JComboBox<>();
        txtBuscarUs = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jButtonEliminarUsuarios = new javax.swing.JButton();
        txtIdUs = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        INICIO.setBackground(new java.awt.Color(255, 204, 102));
        INICIO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        INICIO.setForeground(new java.awt.Color(255, 255, 255));
        INICIO.setText("Inicio");
        INICIO.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        INICIO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });
        getContentPane().add(INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 42));

        CLIENTES.setBackground(new java.awt.Color(255, 204, 102));
        CLIENTES.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLIENTES.setForeground(new java.awt.Color(255, 255, 255));
        CLIENTES.setText("Clientes");
        CLIENTES.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        CLIENTES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIENTESActionPerformed(evt);
            }
        });
        getContentPane().add(CLIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, 42));

        PRODUCTOS.setBackground(new java.awt.Color(255, 204, 102));
        PRODUCTOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PRODUCTOS.setForeground(new java.awt.Color(255, 255, 255));
        PRODUCTOS.setText("Productos");
        PRODUCTOS.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PRODUCTOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTOSActionPerformed(evt);
            }
        });
        getContentPane().add(PRODUCTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 200, 42));

        NUEVAVENTA.setBackground(new java.awt.Color(255, 204, 102));
        NUEVAVENTA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NUEVAVENTA.setForeground(new java.awt.Color(255, 255, 255));
        NUEVAVENTA.setText("Nueva Venta");
        NUEVAVENTA.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        NUEVAVENTA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NUEVAVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVAVENTAActionPerformed(evt);
            }
        });
        getContentPane().add(NUEVAVENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 200, 42));

        USUARIOS.setBackground(new java.awt.Color(255, 204, 102));
        USUARIOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        USUARIOS.setForeground(new java.awt.Color(255, 255, 255));
        USUARIOS.setText("Usuarios");
        USUARIOS.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        USUARIOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USUARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUARIOSActionPerformed(evt);
            }
        });
        getContentPane().add(USUARIOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 200, 42));

        jPanel4.setBackground(new java.awt.Color(204, 51, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBuscarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProdKeyReleased(evt);
            }
        });
        jPanel4.add(txtBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 193, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 63, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 143));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Brighly Crush", 0, 150)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("COFFEE HOME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 920, 210));

        jLabel2.setFont(new java.awt.Font("Almond Nougat", 0, 120)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 0));
        jLabel2.setText("SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 370, 180));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 76, 77));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Cliente"));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Telefono");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Dirección");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonNuevoCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonNuevoCliente.setText("Nuevo");
        jButtonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoClienteActionPerformed(evt);
            }
        });

        jButtonRegistrarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegistrarCliente.setText("Registrar");
        jButtonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarClienteActionPerformed(evt);
            }
        });

        jButtonModificarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonModificarCliente.setText("Modificar");
        jButtonModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarClienteActionPerformed(evt);
            }
        });

        txtDireccionClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(txtDireccionClientes);

        txtBuscarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscarCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCliKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Buscar");

        EliminarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EliminarCliente.setText("Eliminar");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBuscarCli))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jButtonNuevoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addComponent(jButtonRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonModificarCliente)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                                .addComponent(EliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(32, 32, 32)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jPanel3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 440));

        TableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Telefono", "Dirección", "Estado"
            }
        ));
        TableClientes.setRowHeight(20);
        TableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableClientes);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 620, 440));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Producto"));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Codigo");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Nombre");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Precio");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Cantidad");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Medidas");

        txtCodigoProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdActionPerformed(evt);
            }
        });

        txtNombreProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCantidadProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBoxMedidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chico", "Mediano", "Grande" }));
        jComboBoxMedidas.setName(""); // NOI18N

        jButtonNuevoProd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonNuevoProd.setText("Nuevo");
        jButtonNuevoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoProdActionPerformed(evt);
            }
        });

        jButtonRegistrarProd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegistrarProd.setText("Registrar");
        jButtonRegistrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarProdActionPerformed(evt);
            }
        });

        jButtonModificarProd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonModificarProd.setText("Modificar");
        jButtonModificarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarProdActionPerformed(evt);
            }
        });

        txtIDProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIDProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ID");

        jButtonEliminarProd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEliminarProd.setText("Eliminar");
        jButtonEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButtonEliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel20Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel20Layout.createSequentialGroup()
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIDProd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButtonNuevoProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModificarProd)
                .addGap(8, 8, 8))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(38, 38, 38)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 440));

        TableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Descripción", "Precio", "Cantidad", "Medidad", "Estado"
            }
        ));
        TableProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProductosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableProductos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 620, 440));

        jTabbedPane1.addTab("tab3", jPanel1);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(204, 153, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Producto");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Cant");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 31, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Codigo");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Precio");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 31, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Medida");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        txtCodigoNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoNVActionPerformed(evt);
            }
        });
        txtCodigoNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoNVKeyPressed(evt);
            }
        });
        jPanel8.add(txtCodigoNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 142, 25));

        txtNomProdNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(txtNomProdNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 25));

        txtCantidadNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCantidadNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadNVKeyPressed(evt);
            }
        });
        jPanel8.add(txtCantidadNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 45, 25));

        txtMedidaNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(txtMedidaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 110, 25));

        jButtonEliminarPedido.setText("Eliminar");
        jButtonEliminarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarPedidoMouseClicked(evt);
            }
        });
        jButtonEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPedidoActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("ClienteID");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 70, 30));

        txtNombreCliNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(txtNombreCliNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 140, 23));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText(" Nombre");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 70, 40));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Direccion");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, 20));

        txtDireccionNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDireccionNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionNVActionPerformed(evt);
            }
        });
        jPanel8.add(txtDireccionNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 120, 23));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Total a pagar");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, -1, -1));

        LabelTotarPagar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelTotarPagar.setText("----------");
        jPanel8.add(LabelTotarPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        txtTotalNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTotalNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalNVActionPerformed(evt);
            }
        });
        jPanel8.add(txtTotalNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 45, 25));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Total");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        txtPrecioNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(txtPrecioNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 69, 25));

        TableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre Producto", "Cantidad", "Precio", "Medida", "Total"
            }
        ));
        jScrollPane1.setViewportView(TableVentas);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 919, 299));

        txtClienteIdNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClienteIdNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteIdNVKeyPressed(evt);
            }
        });
        jPanel8.add(txtClienteIdNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 75, 23));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Telefono");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        txtTelefonoNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(txtTelefonoNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 90, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Mesero");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 100, -1));

        txtMesero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel8.add(txtMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 100, 25));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 77, -1));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 500));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Proveedor"));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Nombre");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Usuario");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Password");

        txtNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jButtonNuevoUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonNuevoUsuario.setText("Nuevo");
        jButtonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoUsuarioActionPerformed(evt);
            }
        });

        jButtonRegistrarUsu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegistrarUsu.setText("Registrar");
        jButtonRegistrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarCliente1ActionPerformed(evt);
            }
        });

        jButtonModificarUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonModificarUsuario.setText("Modificar");
        jButtonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarUsuarioActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("Rol");

        txtPasswordUs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPasswordUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordUsActionPerformed(evt);
            }
        });

        jComboBoxRolUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Barista", "Mesero" }));

        txtBuscarUs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscarUs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarUsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarUsKeyReleased(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel36.setText("Buscar");

        jButtonEliminarUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEliminarUsuarios.setText("Eliminar");
        jButtonEliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarUsuariosActionPerformed(evt);
            }
        });

        txtIdUs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("ID");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel21Layout.createSequentialGroup()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel21Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)))
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPasswordUs)
                                    .addComponent(jComboBoxRolUs, 0, 175, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel21Layout.createSequentialGroup()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBuscarUs, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNuevoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRegistrarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModificarUsuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jButtonEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addGap(21, 21, 21)
                        .addComponent(txtIdUs, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarUs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(26, 26, 26)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(32, 32, 32)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtPasswordUs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRolUs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdUs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(25, 25, 25))
        );

        jPanel7.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 440));
        jPanel21.getAccessibleContext().setAccessibleName("Nuevo Usuario");

        TableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Usuario", "Password", "Rol", "Status"
            }
        ));
        TableUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TableUsuarios);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 630, 430));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jTabbedPane1.addTab("tab5", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButtonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarClienteActionPerformed
        if(txtNombre.getText().equals("")||txtTelefono.getText().equals("")
            ||txtDireccionClientes.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        }else{
            clien.setNombre(txtNombre.getText());
            clien.setTelefono(txtTelefono.getText());
            clien.setDireccion(txtDireccionClientes.getText());
            if(daoClient.Registrar(clien)){
                LimpiarTable();
                LimpiarCliente();
                listarClientes();
                JOptionPane.showMessageDialog(null, "Cliente registrado");
            }else{
                JOptionPane.showMessageDialog(null, "Error al registrar");
            }
        }
    }//GEN-LAST:event_jButtonRegistrarClienteActionPerformed

    private void jButtonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoClienteActionPerformed
        LimpiarCliente();
    }//GEN-LAST:event_jButtonNuevoClienteActionPerformed

    private void txtCodigoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdActionPerformed

    private void jButtonRegistrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarProdActionPerformed
        if(txtCodigoProd.getText().equals("")||txtNombreProd.getText().equals("")
            ||txtPrecio.getText().equals("")||txtCantidadProd.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        }else{
            prod.setCodigo(txtCodigoProd.getText());
            prod.setNombrePro(txtNombreProd.getText());
            prod.setPrecio(Double.parseDouble(txtPrecio.getText()));
            prod.setCantidad(Integer.parseInt(txtCantidadProd.getText()));
            prod.setMedida(jComboBoxMedidas.getSelectedItem().toString());
            if(daoProd.Insertar(prod)){
                LimpiarTable();
                LimpiarProductos();
                listarProductos();
                JOptionPane.showMessageDialog(null, "Producto registrado");
            }else{
                JOptionPane.showMessageDialog(null, "Error al registrar");
            }
        }
    }//GEN-LAST:event_jButtonRegistrarProdActionPerformed

    private void txtIDProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProdActionPerformed

    private void jButtonModificarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarProdActionPerformed
       if(txtIDProd.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
       }else{
            if(!"".equals(txtCodigoProd.getText())||!"".equals(txtNombreProd.getText())||!"".equals(txtPrecio.getText())||!"".equals(txtCantidadProd.getText())){
                prod.setCodigo(txtCodigoProd.getText());
                prod.setNombrePro(txtNombreProd.getText());
                prod.setPrecio(Double.parseDouble(txtPrecio.getText()));
                prod.setCantidad(Integer.parseInt(txtCantidadProd.getText()));
                prod.setMedida(jComboBoxMedidas.getSelectedItem().toString());
                prod.setId(Integer.parseInt(txtIDProd.getText()));
                daoProd.Modificar(prod);
                LimpiarTable();
                LimpiarProductos();
                listarProductos();
                JOptionPane.showMessageDialog(null, "Producto Modificado");
            }else{
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }
       }
    }//GEN-LAST:event_jButtonModificarProdActionPerformed

    private void txtCodigoNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoNVActionPerformed

    private void jButtonEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPedidoActionPerformed
        modelo = (DefaultTableModel) TableVentas.getModel();
        modelo.removeRow(TableVentas.getSelectedRow());
        TotalPagar();
        txtCodigoNV.requestFocus();
    }//GEN-LAST:event_jButtonEliminarPedidoActionPerformed

    private void txtDireccionNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionNVActionPerformed

    private void txtCodigoNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoNVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(txtCodigoNV.getText())){
                String codigo = txtCodigoNV.getText();
                prod = daoProd.BuscarProductos(codigo);
                if(prod.getNombrePro() != null){
                    txtNomProdNV.setText(""+prod.getNombrePro());
                    txtPrecioNV.setText(""+prod.getPrecio());
                    txtMedidaNV.setText(""+prod.getMedida());
                    txtCantidadNV.requestFocus();
                }
                else{
                    LimpiarVenta();
                    txtCodigoNV.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Ingrese el codigo del producto");
                txtCodigoNV.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCodigoNVKeyPressed

    private void txtTotalNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalNVActionPerformed

    private void txtCantidadNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadNVKeyPressed
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(!"".equals(txtCantidadNV.getText())){
                String codigo = txtCodigoNV.getText();
                String nombre = txtNomProdNV.getText();
                int cantidad = Integer.parseInt(txtCantidadNV.getText());
                double precio = Double.parseDouble(txtPrecioNV.getText());
                String medida = txtMedidaNV.getText();
                double total = cantidad*precio;
                item = item +1;
                DefaultTableModel model = (DefaultTableModel) TableVentas.getModel();
                for(int i = 0; i < TableVentas.getRowCount(); i++){
                    if(TableVentas.getValueAt(i, 1).equals(txtNomProdNV.getText())){
                        JOptionPane.showMessageDialog(null, "El producto ya esta registrado en la venta");
                        return;
                    }
                }
                ArrayList lista = new ArrayList();
                lista.add(item);
                lista.add(codigo);
                lista.add(nombre);
                lista.add(cantidad);
                lista.add(precio);
                lista.add(medida);
                lista.add(total);
                Object[] ob = new Object[6];
                ob[0] = lista.get(1);
                ob[1] = lista.get(2);
                ob[2] = lista.get(3);
                ob[3] = lista.get(4);
                ob[4] = lista.get(5);
                ob[5] = lista.get(6);
                model.addRow(ob);
                TableVentas.setModel(model);
                TotalPagar();
                LimpiarVenta();
                txtCodigoNV.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(null,"Ingrese una cantidad");
            }
        }
    }//GEN-LAST:event_txtCantidadNVKeyPressed

    private void jButtonEliminarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarPedidoMouseClicked
       
    }//GEN-LAST:event_jButtonEliminarPedidoMouseClicked

    private void txtClienteIdNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteIdNVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(txtClienteIdNV.getText())){
                int id = Integer.parseInt(txtClienteIdNV.getText());
                clien = daoClient.BuscarCliente(id);
                if(clien.getNombre() != null){
                    txtNombreCliNV.setText("" + clien.getNombre());
                    txtTelefonoNV.setText("" + clien.getTelefono());
                    txtDireccionNV.setText("" + clien.getDireccion());
                }
                else{
                    txtClienteIdNV.setText("");
                    JOptionPane.showMessageDialog(null, "El cliente no existe");
                }
            }
        }
    }//GEN-LAST:event_txtClienteIdNVKeyPressed

    private void PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTOSActionPerformed
        LimpiarTable();
        listarProductos();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_PRODUCTOSActionPerformed

    private void CLIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIENTESActionPerformed
        LimpiarTable();
        listarClientes();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_CLIENTESActionPerformed

    private void jButtonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarClienteActionPerformed
       if(txtIdCli.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
        }else{
            if(!"".equals(txtNombre.getText())||!"".equals(txtTelefono.getText())||!"".equals(txtDireccionClientes.getText())){
                clien.setNombre(txtNombre.getText());
                clien.setTelefono(txtTelefono.getText());
                clien.setDireccion(txtDireccionClientes.getText());
                clien.setId(Integer.parseInt(txtIdCli.getText()));
                daoClient.Modificar(clien);
                LimpiarTable();
                LimpiarCliente();
                listarClientes();
                JOptionPane.showMessageDialog(null, "Cliente Modificado");
            } 
            else{
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }
       }
    }//GEN-LAST:event_jButtonModificarClienteActionPerformed

    private void TableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientesMouseClicked
        int fila = TableClientes.rowAtPoint(evt.getPoint());
            txtIdCli.setText(TableClientes.getValueAt(fila, 0).toString());
            txtNombre.setText(TableClientes.getValueAt(fila, 1).toString());
            txtTelefono.setText(TableClientes.getValueAt(fila, 2).toString());
            txtDireccionClientes.setText(TableClientes.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_TableClientesMouseClicked

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        if(!"".equals(txtIdCli.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null, "Seguro de eliminar");
            if(pregunta == 0){
                int id = Integer.parseInt(txtIdCli.getText());
                daoClient.EliminarCliente(id);
                LimpiarTable();
                LimpiarCliente();
                listarClientes();
                JOptionPane.showMessageDialog(null, "Cliente eliminado");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }
        }
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void jButtonNuevoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoProdActionPerformed
        LimpiarProductos();
    }//GEN-LAST:event_jButtonNuevoProdActionPerformed

    private void TableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProductosMouseClicked
        int fila = TableProductos.rowAtPoint(evt.getPoint());
            txtIDProd.setText(TableProductos.getValueAt(fila, 0).toString());
            txtCodigoProd.setText(TableProductos.getValueAt(fila, 1).toString());
            txtNombreProd.setText(TableProductos.getValueAt(fila, 2).toString());
            txtPrecio.setText(TableProductos.getValueAt(fila, 3).toString());
            txtCantidadProd.setText(TableProductos.getValueAt(fila, 4).toString());
            jComboBoxMedidas.setSelectedItem(TableProductos.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_TableProductosMouseClicked

    private void jButtonEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProdActionPerformed
        if(!"".equals(txtIDProd.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null, "Seguro de eliminar");
            if(pregunta == 0){
                int id = Integer.parseInt(txtIDProd.getText());
                daoProd.EliminarProducto(id);
                LimpiarTable();
                LimpiarProductos();
                listarProductos();
                JOptionPane.showMessageDialog(null, "Producto eliminado");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }
        }
    }//GEN-LAST:event_jButtonEliminarProdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegistrarVentas();
        RegistrarDetalles();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NUEVAVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVAVENTAActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_NUEVAVENTAActionPerformed

    private void jButtonRegistrarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCliente1ActionPerformed
        if(txtNombreUsuario.getText().equals("")||txtUsuario.getText().equals("")
            ||txtPasswordUs.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        }else{
            usuario.setNombre(txtNombreUsuario.getText());
            usuario.setUsuario(txtUsuario.getText());
            usuario.setPassword(txtPasswordUs.getText());
            usuario.setRol(jComboBoxRolUs.getSelectedItem().toString());
            if(daoUsuario.RegistrarUs(usuario)){
                LimpiarTable();
                LimpiarUsuarios();
                listarUsuarios();
                JOptionPane.showMessageDialog(null, "Usuario registrado");
            }else{
                JOptionPane.showMessageDialog(null, "Error al registrar");
            }
        }
    }//GEN-LAST:event_jButtonRegistrarCliente1ActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtPasswordUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordUsActionPerformed

    private void txtBuscarUsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsKeyPressed
        
    }//GEN-LAST:event_txtBuscarUsKeyPressed

    private void txtBuscarUsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsKeyReleased
        LimpiarTable();
        listarUsuarios();
    }//GEN-LAST:event_txtBuscarUsKeyReleased

    private void txtBuscarCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCliKeyReleased
        LimpiarTable();
        listarClientes();
    }//GEN-LAST:event_txtBuscarCliKeyReleased

    private void txtBuscarProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProdKeyReleased
        LimpiarTable();
        listarProductos();
    }//GEN-LAST:event_txtBuscarProdKeyReleased

    private void jButtonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarUsuarioActionPerformed
        if(txtIdUs.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
       }else{
            if(!"".equals(txtNombreUsuario.getText())||!"".equals(txtUsuario.getText())||!"".equals(txtPasswordUs.getText())){
                usuario.setNombre(txtNombreUsuario.getText());
                usuario.setUsuario(txtUsuario.getText());
                usuario.setPassword(txtPasswordUs.getText());
                usuario.setRol(jComboBoxRolUs.getSelectedItem().toString());
                usuario.setId(Integer.parseInt(txtIdUs.getText()));
                daoUsuario.ModificarUs(usuario);
                LimpiarTable();
                LimpiarUsuarios();
                listarUsuarios();
                JOptionPane.showMessageDialog(null, "Usuario Modificado");
            }else{
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }
       }
    }//GEN-LAST:event_jButtonModificarUsuarioActionPerformed

    private void USUARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUARIOSActionPerformed
        LimpiarTable();
        listarUsuarios();
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_USUARIOSActionPerformed

    private void jButtonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoUsuarioActionPerformed
        LimpiarUsuarios();
    }//GEN-LAST:event_jButtonNuevoUsuarioActionPerformed

    private void jButtonEliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarUsuariosActionPerformed
        if(!"".equals(txtIdUs.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null, "Seguro de eliminar");
            if(pregunta == 0){
                int id = Integer.parseInt(txtIdUs.getText());
                daoUsuario.EliminarUs(id);
                LimpiarTable();
                LimpiarUsuarios();
                listarUsuarios();
                JOptionPane.showMessageDialog(null, "Usuario eliminado");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }
        }
    }//GEN-LAST:event_jButtonEliminarUsuariosActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_INICIOActionPerformed

    private void TableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsuariosMouseClicked
        int fila = TableUsuarios.rowAtPoint(evt.getPoint());
            txtIdUs.setText(TableUsuarios.getValueAt(fila, 0).toString());
            txtNombreUsuario.setText(TableUsuarios.getValueAt(fila, 1).toString());
            txtUsuario.setText(TableUsuarios.getValueAt(fila, 2).toString());
            txtPasswordUs.setText(TableUsuarios.getValueAt(fila, 3).toString());
            jComboBoxRolUs.setSelectedItem(TableUsuarios.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_TableUsuariosMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CLIENTES;
    private javax.swing.JButton EliminarCliente;
    public javax.swing.JButton INICIO;
    private javax.swing.JLabel LabelTotarPagar;
    public javax.swing.JButton NUEVAVENTA;
    public javax.swing.JButton PRODUCTOS;
    public javax.swing.JTable TableClientes;
    public javax.swing.JTable TableProductos;
    private javax.swing.JTable TableUsuarios;
    private javax.swing.JTable TableVentas;
    public javax.swing.JButton USUARIOS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEliminarPedido;
    private javax.swing.JButton jButtonEliminarProd;
    private javax.swing.JButton jButtonEliminarUsuarios;
    public javax.swing.JButton jButtonModificarCliente;
    public javax.swing.JButton jButtonModificarProd;
    private javax.swing.JButton jButtonModificarUsuario;
    public javax.swing.JButton jButtonNuevoCliente;
    public javax.swing.JButton jButtonNuevoProd;
    private javax.swing.JButton jButtonNuevoUsuario;
    public javax.swing.JButton jButtonRegistrarCliente;
    public javax.swing.JButton jButtonRegistrarProd;
    private javax.swing.JButton jButtonRegistrarUsu;
    public javax.swing.JComboBox<Object> jComboBoxMedidas;
    private javax.swing.JComboBox<String> jComboBoxRolUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField txtBuscarCli;
    public javax.swing.JTextField txtBuscarProd;
    private javax.swing.JTextField txtBuscarUs;
    private javax.swing.JTextField txtCantidadNV;
    public javax.swing.JTextField txtCantidadProd;
    private javax.swing.JTextField txtClienteIdNV;
    private javax.swing.JTextField txtCodigoNV;
    public javax.swing.JTextField txtCodigoProd;
    public javax.swing.JTextPane txtDireccionClientes;
    private javax.swing.JTextField txtDireccionNV;
    public javax.swing.JTextField txtIDProd;
    public javax.swing.JTextField txtIdCli;
    private javax.swing.JTextField txtIdUs;
    private javax.swing.JTextField txtMedidaNV;
    private javax.swing.JTextField txtMesero;
    private javax.swing.JTextField txtNomProdNV;
    public javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCliNV;
    public javax.swing.JTextField txtNombreProd;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtPasswordUs;
    public javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioNV;
    public javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoNV;
    private javax.swing.JTextField txtTotalNV;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void listarClientes(){
        List<Clientes> lista = daoClient.ListaClientes(txtBuscarCli.getText());
        modelo = (DefaultTableModel) TableClientes.getModel();
        Object[] ob = new Object[5];
        for(int i = 0; i < lista.size(); i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getTelefono();
            ob[3]=lista.get(i).getDireccion();
            ob[4]=lista.get(i).getEstado();
            modelo.addRow(ob);
        }
        TableClientes.setModel(modelo);
    }
    public void LimpiarTable(){
        for(int i = 0; i < modelo.getRowCount(); i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    private void LimpiarCliente(){
        txtIdCli.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDireccionClientes.setText("");
    }
    private void LimpiarProductos(){
        txtCodigoProd.setText("");
        txtNombreProd.setText("");
        txtPrecio.setText("");
        txtCantidadProd.setText("");
        jComboBoxMedidas.setSelectedItem(null);
        txtIDProd.setText("");
    }
    
    public void listarProductos(){
        List<Productos> lista = daoProd.ListaProductos(txtBuscarProd.getText());
        modelo = (DefaultTableModel) TableProductos.getModel();
        Object[] ob = new Object[7];
        for(int i = 0; i < lista.size(); i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getCodigo();
            ob[2]=lista.get(i).getNombrePro();
            ob[3]=lista.get(i).getPrecio();
            ob[4]=lista.get(i).getCantidad();
            ob[5]=lista.get(i).getMedida();
            ob[6]=lista.get(i).getEstado();
            modelo.addRow(ob);
        }
        TableProductos.setModel(modelo);
    }
    
    public void listarUsuarios(){
        List<Usuarios> lista = daoUsuario.ListaUsuarios(txtBuscarUs.getText());
        modelo = (DefaultTableModel) TableUsuarios.getModel();
        Object[] ob = new Object[6];
        for(int i = 0; i < lista.size(); i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getNombre();
            ob[2]=lista.get(i).getUsuario();
            ob[3]=lista.get(i).getPassword();
            ob[4]=lista.get(i).getRol();
            ob[5]=lista.get(i).getStatus();
            modelo.addRow(ob);
        }
        TableUsuarios.setModel(modelo);
    }
    private void TotalPagar(){
        totalPagar = 0.00;
        int numFila = TableVentas.getRowCount();
        for(int i = 0; i < numFila; i++){
            double calcular = Double.parseDouble(String.valueOf(TableVentas.getModel().getValueAt(i,5)));
            totalPagar = totalPagar + calcular;
        }
        LabelTotarPagar.setText(String.format("%.2f", totalPagar));
    }
    private void LimpiarVenta(){
        txtCodigoNV.setText("");
        txtNomProdNV.setText("");
        txtCantidadNV.setText("");
        txtPrecioNV.setText("");
        txtMedidaNV.setText("");
    }
    private void LimpiarUsuarios(){
        txtNombreUsuario.setText("");
        txtUsuario.setText("");
        txtPasswordUs.setText("");
        jComboBoxMedidas.setSelectedItem(null);
        txtIdUs.setText("");
    }
    private void RegistrarVentas(){
        String cliente = txtNombreCliNV.getText();
        String mesero = txtMesero.getText();
        double totPago = totalPagar;
        ven.setCliente(cliente);
        ven.setMesero(mesero);
        ven.setTotal(totPago);
        daoVen.IngresarVenta(ven);
    }
    private void RegistrarDetalles(){
        int id = daoVen.IdVenta();
        for(int i = 0; i < TableVentas.getRowCount(); i++){
            String cod = TableVentas.getValueAt(i, 0).toString();
            int cant = Integer.parseInt(TableVentas.getValueAt(i, 2).toString());
            double precio = Double.parseDouble(TableVentas.getValueAt(i, 3).toString());
            detaVent.setCodigoProd(cod);
            detaVent.setCantidad(cant);
            detaVent.setPrecio(precio);
            detaVent.setIdVenta(id);
            daoVen.IngresarDetalles(detaVent);
        }
    }

}